using System.Collections.Generic;
using Dreamteck.Splines;
using UnityEngine;
#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.SceneManagement;
#endif

/// <summary>
/// Editor-only authoring tool that forces the conveyor belt to actually look like its spline.
///
/// <para><b>What it does.</b> Attach this to the object carrying the <c>SplineComputer</c> and its
/// <c>SplineMesh</c> belt. Press <b>Update Mesh</b> and the spline is rebuilt, the current
/// Thickness Modifier is baked into every point's size, and the belt mesh is refit to the current
/// Width Modifier and Mesh Density. Nothing else on the GameObject or its children is touched — no
/// collider, no arrows, no slots.</para>
///
/// <para><b>Not a shape tool.</b> This never touches the spline's points — it takes whatever shape
/// is already on it, however it got there (hand-edited in the Scene view, generated by
/// <c>ConveyorPathBuilder</c>, or whatever else).</para>
///
/// <para><b>Width Modifier.</b> Scales every channel's own mesh width, relative to however it was
/// authored (captured as a baseline the first time Update Mesh runs). 1 leaves it untouched.</para>
///
/// <para><b>Thickness Modifier.</b> Scales each spline point's own <c>size</c> — the same value
/// that drives the Spline Computer's "Draw Thickness" gizmo. Spline Mesh multiplies every channel's
/// mesh scale and offset by that point size at each vertex, so this is the master scale Width
/// Modifier is layered on top of. Same baseline-on-first-press, same no-op-at-1 behaviour as Width
/// Modifier.</para>
///
/// <para><b>Editor only.</b> Every method lives inside <c>#if UNITY_EDITOR</c> and there is no
/// Awake/Start/Update, so nothing here can execute in a player build. The serialized fields
/// deliberately sit outside the guard so the component's serialized layout is identical in the
/// editor and in a build.</para>
/// </summary>
[DisallowMultipleComponent]
public sealed class ConveyorMeshUpdater : MonoBehaviour
{
    // See the class summary for why these sit outside the UNITY_EDITOR guard.
#pragma warning disable CS0169, CS0414, CS0649

    [Header("References (auto-filled; drag only if this is not on the conveyor)")]
    [Tooltip("The conveyor's path. Auto-filled from this GameObject.")]
    [SerializeField] private SplineComputer _splineComputer;

    [Tooltip("The belt mesh that rides the spline. Auto-filled from this GameObject.")]
    [SerializeField] private SplineMesh _splineMesh;

    [Header("Density")]
    [Tooltip("Mesh tiles per world unit of spline. Each tile is one segment of the extrusion, so " +
             "this is what actually controls how smooth the belt is. Leave at 0 to leave the tile " +
             "counts exactly as authored.")]
    [Min(0f)]
    [SerializeField] private float _meshDensity;

    [Tooltip("Allow the belt mesh to use 32-bit indices. Unity's default 16-bit index format caps " +
             "a mesh at 65535 vertices; a long or dense conveyor blows straight past that, and " +
             "Dreamteck then logs \"exceeds the maximum vertex count\" and writes a broken mesh. " +
             "Leave this on unless you are targeting hardware without 32-bit index support.")]
    [SerializeField] private bool _use32BitMeshIndices = true;

    [Header("Width")]
    [Tooltip("Scale of every belt channel's own mesh width, relative to however it was authored " +
             "(captured the first time Update Mesh runs). 1 leaves it untouched.")]
    [Min(0.01f)]
    [SerializeField] private float _widthModifier = 1f;

    [Header("Thickness")]
    [Tooltip("Scale of the spline's own point size — the value driving the Spline Computer's " +
             "\"Draw Thickness\" gizmo, and the master scale Spline Mesh multiplies every channel's " +
             "width/offset by at each point. Relative to however each point was authored (captured " +
             "the first time Update Mesh runs). 1 leaves it untouched.")]
    [Min(0.01f)]
    [SerializeField] private float _thicknessModifier = 1f;

    // ── Width baseline (persisted; captured automatically, not hand-edited) ────────────────────
    [SerializeField, HideInInspector] private List<float> _channelScaleBase = new();

    // ── Thickness baseline (persisted; captured automatically, not hand-edited) ───────────────
    [SerializeField, HideInInspector] private List<float> _pointSizeBase = new();

#pragma warning restore CS0169, CS0414, CS0649

#if UNITY_EDITOR

    private const string UpdateUndoName = "Update Conveyor Mesh";

    // Fills the references in when the component is first added, so dropping it on the Conveyor
    // is all the setup there is.
    private void Reset()
    {
        ResolveReferences();
    }

    /// <summary>
    /// Fills in every reference that is still null and captures the baselines if they have not
    /// been captured yet. Safe to call repeatedly; never overwrites something assigned by hand and
    /// never re-captures a baseline that already exists.
    /// </summary>
    public void ResolveReferences()
    {
        if (_splineComputer == null) _splineComputer = GetComponent<SplineComputer>();
        if (_splineMesh == null) _splineMesh = GetComponent<SplineMesh>();

        CaptureWidthBaseIfNeeded();
        CapturePointSizeBaseIfNeeded();
    }

    // ── Button: update ──────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Forces the spline to rebuild, then the belt mesh onto it — the whole reason this component
    /// exists.
    /// </summary>
    public void UpdateMesh()
    {
        ResolveReferences();

        if (!CanEdit()) return;
        if (_splineComputer == null || _splineMesh == null)
        {
            LogError("no Spline Computer or Spline Mesh on this GameObject. Attach this to the " +
                     "Conveyor's root.");
            return;
        }

        Undo.RecordObjects(new Object[] { _splineComputer, _splineMesh }, UpdateUndoName);

        // Selecting these objects in the Hierarchy is what normally fixes a stale-looking belt —
        // Dreamteck's own SplineComputerEditor/SplineUserEditor call exactly this on OnEnable, which
        // re-acquires the MeshFilter/MeshRenderer references RebuildImmediate() writes into. Calling
        // it here reproduces that without needing the user to click anything.
        _splineComputer.EditorAwake();
        _splineMesh.EditorAwake();

        // Must happen before either mesh is rebuilt below: the index format decides how many vertices
        // a mesh can hold at all, and a rebuild that overflows 16-bit indices writes a broken mesh.
        ApplyMeshIndexFormat();

        // Must happen before the spline rebuild below, so the forced rebuild bakes the new point
        // sizes into the spline's evaluate cache before the belt mesh samples it.
        CapturePointSizeBaseIfNeeded();
        ApplyThickness();

        // Forced and immediate, not the deferred Rebuild() — this button exists specifically to show
        // the result without needing the Scene view to select anything.
        _splineComputer.RebuildImmediate();
        var length = _splineComputer.CalculateLength();

        CaptureWidthBaseIfNeeded();

        // Counts first: they decide how many segments the extrusion has, so they must be in place
        // before the mesh is told to rebuild.
        var tiles = ApplyTileCounts(length);

        ApplyWidth();
        _splineMesh.RebuildImmediate();
        MarkDirty(_splineMesh);

        MarkDirty(this);
        Log($"spline rebuilt (length {length:F1}), {tiles}.");
    }

    // ── Mesh index format ────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Puts the belt mesh on the index format chosen by Use 32 Bit Mesh Indices.
    ///
    /// <para>Dreamteck's MeshGenerator defaults to 16-bit indices, which caps a mesh at 65535
    /// vertices and only reports the overflow after the fact (MeshGenerator.WriteMesh) — by which
    /// point it has already written a broken mesh. A conveyor long or dense enough to need this is
    /// exactly the kind this component exists to author, so the format is raised here rather than
    /// left to be found by hand in the Spline Mesh's Vertices foldout.</para>
    ///
    /// <para>Public because a reshaping tool must call it <i>before</i> it writes points: any
    /// SplineComputer.SetPoints rebuilds the meshes immediately, so a builder that waits for
    /// <see cref="UpdateMesh"/> to set the format has already overflowed once by then.</para>
    /// </summary>
    public void ApplyMeshIndexFormat()
    {
        if (_splineMesh == null) return;

        _splineMesh.meshIndexFormat = _use32BitMeshIndices
            ? UnityEngine.Rendering.IndexFormat.UInt32
            : UnityEngine.Rendering.IndexFormat.UInt16;
    }

    // ── Width ────────────────────────────────────────────────────────────────────────────────

    private void CaptureWidthBaseIfNeeded()
    {
        if (_channelScaleBase.Count != 0 || _splineMesh == null) return;

        var channelCount = _splineMesh.GetChannelCount();
        _channelScaleBase = new List<float>(channelCount);

        for (var i = 0; i < channelCount; i++)
        {
            var channel = _splineMesh.GetChannel(i);
            _channelScaleBase.Add(channel.GetMeshCount() > 0 ? channel.GetMesh(0).scale.x : 1f);
        }
    }

    // Scales every channel's own mesh width relative to its captured baseline.
    private void ApplyWidth()
    {
        if (_splineMesh == null || _channelScaleBase.Count == 0) return;

        var channelCount = Mathf.Min(_splineMesh.GetChannelCount(), _channelScaleBase.Count);
        for (var i = 0; i < channelCount; i++)
        {
            var channel = _splineMesh.GetChannel(i);
            if (channel.GetMeshCount() == 0) continue;

            var meshDef = channel.GetMesh(0);
            meshDef.scale = new Vector3(_channelScaleBase[i] * _widthModifier, meshDef.scale.y, meshDef.scale.z);
        }
    }

    // ── Thickness (the spline's own point size, not a channel value) ───────────────────────────

    private void CapturePointSizeBaseIfNeeded()
    {
        if (_pointSizeBase.Count != 0 || _splineComputer == null) return;

        _pointSizeBase = new List<float>(_splineComputer.pointCount);
        for (var i = 0; i < _splineComputer.pointCount; i++)
            _pointSizeBase.Add(_splineComputer.GetPointSize(i));
    }

    // Scales every point's size relative to its captured baseline. This is the value Spline Mesh
    // multiplies every channel's mesh scale and offset by at each vertex (see SplineMesh.Extrude),
    // and the same value the Spline Computer's Draw Thickness gizmo visualises.
    private void ApplyThickness()
    {
        if (_splineComputer == null || _pointSizeBase.Count == 0) return;

        // Every point is covered, not just the ones the baseline happens to have an entry for. A
        // reshaping tool (ConveyorPathBuilder) replaces the spline's points wholesale and can easily
        // leave more of them than were here when the baseline was captured; those extra points used
        // to fall outside the loop entirely and keep SplinePoint's default size of 1. A conveyor's
        // thickness is uniform, so the last captured value is the right one to carry across the
        // remainder.
        for (var i = 0; i < _splineComputer.pointCount; i++)
        {
            var baseSize = _pointSizeBase[Mathf.Min(i, _pointSizeBase.Count - 1)];
            _splineComputer.SetPointSize(i, baseSize * _thicknessModifier);
        }
    }

    // ── Tile counts (the actual smoothness control) ──────────────────────────────────────────

    // This is the fix for "smooth only after entering play mode". A channel's tile count is not a
    // texturing detail — each repetition is one segment of the extrusion, and the belt's source mesh
    // has vertex groups only at its two ends, so a count of 10 is literally a 10-sided polygon no
    // matter how smooth the spline underneath it is.
    private string ApplyTileCounts(float length)
    {
        if (_meshDensity <= 0f) return "tile counts left as authored";

        var beltCount = Mathf.Max(1, Mathf.CeilToInt(length * _meshDensity));
        for (var i = 0; i < _splineMesh.GetChannelCount(); i++)
            _splineMesh.GetChannel(i).count = beltCount;

        return $"{beltCount} tiles at {_meshDensity:F2}/unit";
    }

    // ── Plumbing ─────────────────────────────────────────────────────────────────────────────

    private bool CanEdit()
    {
        if (!EditorApplication.isPlayingOrWillChangePlaymode) return true;

        LogError("cannot update the conveyor mesh in play mode. Exit play mode and try again.");
        return false;
    }

    private static void MarkDirty(Object target)
    {
        if (target == null) return;

        EditorUtility.SetDirty(target);

        if (target is Component component && component.gameObject.scene.IsValid())
            EditorSceneManager.MarkSceneDirty(component.gameObject.scene);
    }

    private void Log(string message) => Debug.Log($"<b>Conveyor Mesh</b>: {message}", this);
    private void LogError(string message) => Debug.LogError($"<b>Conveyor Mesh</b>: {message}", this);

#endif
}
